# Generated by Django 4.2.6 on 2023-11-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileAfterLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='Ibrahim')),
                ('password', models.TextField(default='1234')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileBeforeLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='Ibrahim')),
                ('password', models.TextField(default='1234')),
                ('email', models.EmailField(default='1234', max_length=254)),
                ('phoneNumber', models.TextField(default='1234')),
            ],
        ),
    ]
