# Generated by Django 4.2.6 on 2023-11-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofileafterlogin_userprofilebeforelogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilebeforelogin',
            name='role',
            field=models.TextField(default='Investor'),
        ),
    ]
