# Generated by Django 4.2.6 on 2023-11-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofilebeforelogin_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProperProfileCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField(default=100)),
                ('username', models.TextField(default='Ibrahim')),
                ('password', models.TextField(default='1234')),
                ('email', models.EmailField(default='1234', max_length=254)),
                ('phoneNumber', models.TextField(default='1234')),
                ('role', models.TextField(default='Investor')),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('city', models.CharField(default='Lahore', max_length=100)),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('postalCode', models.IntegerField(default=54000)),
                ('latest_job', models.CharField(default='student', max_length=1000)),
                ('salary_Income_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('is_married', models.CharField(default='unmarried', max_length=200)),
                ('cnic_number', models.CharField(blank=True, default='000000000', max_length=15)),
            ],
        ),
    ]
