# Generated by Django 4.2.6 on 2023-11-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_properprofilecreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properprofilecreation',
            name='postalCode',
            field=models.IntegerField(default=54000, max_length=100000),
        ),
    ]
