# Generated by Django 4.2.6 on 2023-11-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('industry_expertise', models.CharField(max_length=100, verbose_name='Industry/Field of Expertise')),
                ('job_title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('previous_venture', models.TextField(verbose_name='Previous Ventures/Projects (with descriptions and outcomes)')),
                ('years_of_experience', models.PositiveIntegerField(verbose_name='Years of Experience as an Entrepreneur')),
                ('achievements', models.TextField(verbose_name='Achievements or Recognitions')),
                ('key_skills', models.CharField(max_length=255, verbose_name='Key Skills (e.g., leadership, project management, finance)')),
                ('highest_education_attained', models.CharField(max_length=100, verbose_name='Highest Level of Education Attained')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='entrepreneur_profiles/', verbose_name='Profile Image')),
                ('linkedin_profile', models.URLField(blank=True, default='https://twitter.com', null=True, verbose_name='LinkedIn Profile')),
                ('twitter_profile', models.URLField(blank=True, default='https://twitter.com', null=True, verbose_name='Twitter Profile')),
                ('bio', models.TextField()),
            ],
        ),
    ]
