# Generated by Django 4.2.6 on 2023-11-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_entrepreneurprofile_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='UserId',
            field=models.IntegerField(default=1),
        ),
    ]
