# Generated by Django 4.2.6 on 2023-11-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='UserId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Project ID'),
        ),
    ]
