# Generated by Django 4.2.6 on 2023-11-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_project_id_project_userid_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Project ID'),
        ),
    ]
