# Generated by Django 4.2.6 on 2023-11-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='linkedin_profile',
            field=models.TextField(blank=True, default='https://twitter.com', null=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='profile_image',
            field=models.TextField(blank=True, default='image', null=True, verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='entrepreneurprofile',
            name='twitter_profile',
            field=models.TextField(blank=True, default='https://twitter.com', null=True, verbose_name='Twitter Profile'),
        ),
    ]
