# Generated by Django 4.2.6 on 2023-11-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_entrepreneurprofile_linkedin_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProject',
            fields=[
                ('UserId', models.IntegerField(default=1)),
                ('investment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Project ID')),
                ('field_of_investment', models.CharField(max_length=255, verbose_name='Project Name')),
                ('years_of_investment', models.CharField(max_length=100, verbose_name='Field')),
                ('minimum_investment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Investment (USD)')),
                ('minimum_profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Guaranteed Profit (USD)')),
                ('allowed_risk', models.FloatField(verbose_name='Chance of Risk (%)')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('time_scale_allowed', models.CharField(max_length=50, verbose_name='Time Scale')),
            ],
        ),
    ]
