# Generated by Django 4.2.6 on 2023-11-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_investorproject_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorproject',
            name='years_of_investment',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Field'),
        ),
    ]
