# Generated by Django 4.2.6 on 2023-11-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_investorproject_years_of_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorproject',
            name='years_of_investment',
            field=models.CharField(max_length=255, verbose_name='Field'),
        ),
    ]
