# Generated by Django 4.2.6 on 2024-01-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_investorproject_years_of_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorproject',
            name='allowed_risk',
            field=models.CharField(max_length=255, verbose_name='Chance of Risk (%)'),
        ),
    ]
