# Generated by Django 4.2.6 on 2024-01-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_investorproject_allowed_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorproject',
            name='minimum_investment',
            field=models.CharField(max_length=50, verbose_name='Minimum Investment (USD)'),
        ),
        migrations.AlterField(
            model_name='investorproject',
            name='minimum_profit',
            field=models.CharField(max_length=50, verbose_name='Guaranteed Profit (USD)'),
        ),
    ]
